import { BuildingProject } from '../types/architecture';

export const TEMPLATES: { id: string; name: string; description: string; project: BuildingProject }[] = [
  {
    id: 'villa_contemporaine',
    name: 'Villa Contemporaine R+1',
    description: 'Résidence moderne de 145 m² sur 2 niveaux avec baies panoramiques et toiture terrasse.',
    project: {
      id: 'proj_villa_01',
      title: 'Villa Panorama',
      architect: 'Cabinet Archi-Design',
      client: 'Famille Lefebvre',
      location: 'Aix-en-Provence',
      date: '2026-03-15',
      unit: 'm',
      gridSize: 0.5,
      snapToGrid: true,
      dimensions: {
        length: 12.0, // 12m facade
        width: 9.0,   // 9m profondeur
      },
      exteriorWallThickness: 0.30,
      interiorWallThickness: 0.15,
      foundationHeight: 0.40,
      activeFloorLevel: 0,
      materials: {
        facade: 'white_stucco',
        joineryColor: 'black',
        roofMaterial: 'gravel_terrace',
        glassTint: 'clear',
        groundType: 'grass_lawn',
      },
      roof: {
        type: 'flat',
        pitch: 5,
        overhang: 0.30,
        material: 'gravel_terrace',
        parapetHeight: 0.45,
      },
      floors: [
        {
          id: 'floor_rdc',
          level: 0,
          name: 'Rez-de-chaussée (RDC)',
          ceilingHeight: 2.80,
          rooms: [
            {
              id: 'room_living',
              name: 'Séjour & Salon',
              type: 'living',
              x: 0.5,
              y: 0.5,
              width: 6.5,
              length: 5.0,
              floorFinish: 'parquet_oak',
              customColor: '#38bdf8',
            },
            {
              id: 'room_kitchen',
              name: 'Cuisine Ouverte',
              type: 'kitchen',
              x: 7.0,
              y: 0.5,
              width: 4.5,
              length: 4.0,
              floorFinish: 'tile_marble',
              customColor: '#f59e0b',
            },
            {
              id: 'room_suite_rdc',
              name: 'Suite Parentale',
              type: 'bedroom',
              x: 0.5,
              y: 5.5,
              width: 4.5,
              length: 3.0,
              floorFinish: 'parquet_oak',
              customColor: '#818cf8',
            },
            {
              id: 'room_sdb_rdc',
              name: 'Salle d’Eau',
              type: 'bathroom',
              x: 5.0,
              y: 5.5,
              width: 2.5,
              length: 3.0,
              floorFinish: 'tile_slate',
              customColor: '#06b6d4',
            },
            {
              id: 'room_hall',
              name: 'Hall d’Entrée & Dégagement',
              type: 'hallway',
              x: 7.5,
              y: 4.5,
              width: 4.0,
              length: 4.0,
              floorFinish: 'tile_marble',
              customColor: '#94a3b8',
            },
          ],
          openings: [
            {
              id: 'op_bay_south_1',
              type: 'sliding_bay',
              wall: 'south',
              offset: 1.5,
              width: 3.6,
              height: 2.4,
              sillHeight: 0.0,
            },
            {
              id: 'op_bay_south_2',
              type: 'sliding_bay',
              wall: 'south',
              offset: 7.5,
              width: 2.4,
              height: 2.4,
              sillHeight: 0.0,
            },
            {
              id: 'op_door_main',
              type: 'entry_door',
              wall: 'north',
              offset: 8.5,
              width: 1.0,
              height: 2.2,
              sillHeight: 0.0,
              swingDirection: 'inward',
            },
            {
              id: 'op_win_west',
              type: 'window_standard',
              wall: 'west',
              offset: 6.0,
              width: 1.4,
              height: 1.3,
              sillHeight: 0.9,
            },
            {
              id: 'op_win_east',
              type: 'window_double',
              wall: 'east',
              offset: 1.5,
              width: 1.6,
              height: 1.3,
              sillHeight: 0.9,
            },
          ],
        },
        {
          id: 'floor_r1',
          level: 1,
          name: 'Étage 1 (R+1)',
          ceilingHeight: 2.60,
          rooms: [
            {
              id: 'room_ch1',
              name: 'Chambre 1 (Junior)',
              type: 'bedroom',
              x: 0.5,
              y: 0.5,
              width: 4.0,
              length: 3.8,
              floorFinish: 'parquet_oak',
              customColor: '#818cf8',
            },
            {
              id: 'room_ch2',
              name: 'Chambre 2 (Invités)',
              type: 'bedroom',
              x: 4.5,
              y: 0.5,
              width: 4.0,
              length: 3.8,
              floorFinish: 'parquet_oak',
              customColor: '#818cf8',
            },
            {
              id: 'room_office',
              name: 'Bureau / Télétravail',
              type: 'office',
              x: 8.5,
              y: 0.5,
              width: 3.0,
              length: 3.8,
              floorFinish: 'parquet_oak',
              customColor: '#10b981',
            },
            {
              id: 'room_sdb_r1',
              name: 'Salle de Bain Familiale',
              type: 'bathroom',
              x: 0.5,
              y: 4.5,
              width: 3.5,
              length: 3.5,
              floorFinish: 'tile_slate',
              customColor: '#06b6d4',
            },
            {
              id: 'room_terrace_r1',
              name: 'Toit Terrasse Privatif',
              type: 'terrace',
              x: 4.5,
              y: 4.5,
              width: 7.0,
              length: 4.0,
              floorFinish: 'terrace_deck',
              customColor: '#64748b',
            },
          ],
          openings: [
            {
              id: 'op_r1_win_1',
              type: 'window_double',
              wall: 'south',
              offset: 1.2,
              width: 1.6,
              height: 1.4,
              sillHeight: 0.8,
            },
            {
              id: 'op_r1_win_2',
              type: 'window_double',
              wall: 'south',
              offset: 5.2,
              width: 1.6,
              height: 1.4,
              sillHeight: 0.8,
            },
            {
              id: 'op_r1_bay_terrace',
              type: 'french_door',
              wall: 'north',
              offset: 6.0,
              width: 2.0,
              height: 2.2,
              sillHeight: 0.0,
            },
          ],
        },
      ],
    },
  },
  {
    id: 'pavillon_plain_pied',
    name: 'Maison Individuelle Plain-Pied',
    description: 'Pavillon familial traditionnel de 105 m² avec toiture 2 pentes en tuiles, garage et 3 chambres.',
    project: {
      id: 'proj_pavillon_02',
      title: 'Pavillon Les Chênes',
      architect: 'Atelier Architecture & Bois',
      client: 'M. et Mme Dupont',
      location: 'Nantes',
      date: '2026-02-20',
      unit: 'm',
      gridSize: 0.5,
      snapToGrid: true,
      dimensions: {
        length: 13.5,
        width: 8.5,
      },
      exteriorWallThickness: 0.30,
      interiorWallThickness: 0.15,
      foundationHeight: 0.35,
      activeFloorLevel: 0,
      materials: {
        facade: 'warm_limestone',
        joineryColor: 'anthracite',
        roofMaterial: 'tile_terracotta',
        glassTint: 'clear',
        groundType: 'grass_lawn',
      },
      roof: {
        type: 'gable',
        pitch: 35,
        overhang: 0.45,
        material: 'tile_terracotta',
        parapetHeight: 0,
      },
      floors: [
        {
          id: 'floor_rdc_pav',
          level: 0,
          name: 'Rez-de-chaussée',
          ceilingHeight: 2.60,
          rooms: [
            {
              id: 'pav_living',
              name: 'Grand Séjour Traversant',
              type: 'living',
              x: 0.5,
              y: 0.5,
              width: 5.5,
              length: 7.5,
              floorFinish: 'tile_marble',
              customColor: '#38bdf8',
            },
            {
              id: 'pav_kitchen',
              name: 'Cuisine Indépendante',
              type: 'kitchen',
              x: 6.0,
              y: 0.5,
              width: 3.5,
              length: 3.5,
              floorFinish: 'tile_slate',
              customColor: '#f59e0b',
            },
            {
              id: 'pav_ch1',
              name: 'Chambre Principale',
              type: 'bedroom',
              x: 9.5,
              y: 0.5,
              width: 3.5,
              length: 3.5,
              floorFinish: 'parquet_oak',
              customColor: '#818cf8',
            },
            {
              id: 'pav_ch2',
              name: 'Chambre 2',
              type: 'bedroom',
              x: 9.5,
              y: 4.5,
              width: 3.5,
              length: 3.5,
              floorFinish: 'parquet_oak',
              customColor: '#818cf8',
            },
            {
              id: 'pav_sdb',
              name: 'Salle d’Eau & WC',
              type: 'bathroom',
              x: 6.0,
              y: 4.5,
              width: 3.5,
              length: 3.5,
              floorFinish: 'tile_slate',
              customColor: '#06b6d4',
            },
          ],
          openings: [
            {
              id: 'pav_bay_south',
              type: 'sliding_bay',
              wall: 'south',
              offset: 1.0,
              width: 3.0,
              height: 2.2,
              sillHeight: 0.0,
            },
            {
              id: 'pav_door_in',
              type: 'entry_door',
              wall: 'north',
              offset: 2.0,
              width: 0.9,
              height: 2.15,
              sillHeight: 0.0,
            },
            {
              id: 'pav_win_kitch',
              type: 'window_standard',
              wall: 'south',
              offset: 7.0,
              width: 1.4,
              height: 1.2,
              sillHeight: 1.0,
            },
            {
              id: 'pav_win_ch1',
              type: 'window_double',
              wall: 'south',
              offset: 10.5,
              width: 1.4,
              height: 1.3,
              sillHeight: 0.85,
            },
            {
              id: 'pav_win_ch2',
              type: 'window_double',
              wall: 'north',
              offset: 10.5,
              width: 1.4,
              height: 1.3,
              sillHeight: 0.85,
            },
          ],
        },
      ],
    },
  },
  {
    id: 'loft_architecte',
    name: 'Loft Scandinave & Verrière',
    description: 'Espace ouvert de 75 m² baigné de lumière, bardage bois naturel et toiture monopente contemporaine.',
    project: {
      id: 'proj_loft_03',
      title: 'Loft Atelier Nordique',
      architect: 'Studio Kroma Design',
      client: 'Projet Démo',
      location: 'Bordeaux',
      date: '2026-03-01',
      unit: 'm',
      gridSize: 0.5,
      snapToGrid: true,
      dimensions: {
        length: 10.0,
        width: 7.5,
      },
      exteriorWallThickness: 0.28,
      interiorWallThickness: 0.12,
      foundationHeight: 0.30,
      activeFloorLevel: 0,
      materials: {
        facade: 'nordic_timber',
        joineryColor: 'black',
        roofMaterial: 'zinc_dark',
        glassTint: 'clear',
        groundType: 'modern_patio',
      },
      roof: {
        type: 'shed',
        pitch: 18,
        overhang: 0.5,
        material: 'zinc_dark',
        parapetHeight: 0,
      },
      floors: [
        {
          id: 'floor_rdc_loft',
          level: 0,
          name: 'Espace de Vie & Atelier',
          ceilingHeight: 3.20,
          rooms: [
            {
              id: 'loft_open_space',
              name: 'Grand Volume Ouvert / Salon / Cuisine',
              type: 'living',
              x: 0.4,
              y: 0.4,
              width: 6.2,
              length: 6.7,
              floorFinish: 'polished_concrete',
              customColor: '#38bdf8',
            },
            {
              id: 'loft_bed',
              name: 'Alcôve Nuit',
              type: 'bedroom',
              x: 6.6,
              y: 0.4,
              width: 3.0,
              length: 3.5,
              floorFinish: 'parquet_oak',
              customColor: '#818cf8',
            },
            {
              id: 'loft_bath',
              name: 'Salle d’Eau Minimaliste',
              type: 'bathroom',
              x: 6.6,
              y: 4.0,
              width: 3.0,
              length: 3.1,
              floorFinish: 'tile_slate',
              customColor: '#06b6d4',
            },
          ],
          openings: [
            {
              id: 'loft_bay_main',
              type: 'sliding_bay',
              wall: 'south',
              offset: 1.0,
              width: 4.2,
              height: 2.8,
              sillHeight: 0.0,
            },
            {
              id: 'loft_door_entry',
              type: 'entry_door',
              wall: 'north',
              offset: 7.5,
              width: 1.0,
              height: 2.3,
              sillHeight: 0.0,
            },
          ],
        },
      ],
    },
  },
  {
    id: 'projet_vierge',
    name: 'Nouveau Projet Vierge (Paramétrique)',
    description: 'Projet neutre de 10m x 8m prêt pour la saisie personnalisée des cotes et cloisons.',
    project: {
      id: 'proj_new_01',
      title: 'Mon Projet Architectural',
      architect: 'Architecte',
      client: 'Maître d’Ouvrage',
      location: 'France',
      date: '2026-03-20',
      unit: 'm',
      gridSize: 0.5,
      snapToGrid: true,
      dimensions: {
        length: 10.0,
        width: 8.0,
      },
      exteriorWallThickness: 0.30,
      interiorWallThickness: 0.15,
      foundationHeight: 0.35,
      activeFloorLevel: 0,
      materials: {
        facade: 'white_stucco',
        joineryColor: 'black',
        roofMaterial: 'tile_terracotta',
        glassTint: 'clear',
        groundType: 'grass_lawn',
      },
      roof: {
        type: 'gable',
        pitch: 30,
        overhang: 0.40,
        material: 'tile_terracotta',
        parapetHeight: 0,
      },
      floors: [
        {
          id: 'floor_rdc_new',
          level: 0,
          name: 'Rez-de-chaussée (RDC)',
          ceilingHeight: 2.70,
          rooms: [
            {
              id: 'room_1',
              name: 'Séjour Principal',
              type: 'living',
              x: 0.5,
              y: 0.5,
              width: 5.0,
              length: 7.0,
              floorFinish: 'parquet_oak',
              customColor: '#38bdf8',
            },
            {
              id: 'room_2',
              name: 'Cuisine / Repas',
              type: 'kitchen',
              x: 5.5,
              y: 0.5,
              width: 4.0,
              length: 3.5,
              floorFinish: 'tile_marble',
              customColor: '#f59e0b',
            },
            {
              id: 'room_3',
              name: 'Chambre 1',
              type: 'bedroom',
              x: 5.5,
              y: 4.0,
              width: 4.0,
              length: 3.5,
              floorFinish: 'parquet_oak',
              customColor: '#818cf8',
            },
          ],
          openings: [
            {
              id: 'op_main_bay',
              type: 'sliding_bay',
              wall: 'south',
              offset: 1.5,
              width: 2.8,
              height: 2.2,
              sillHeight: 0.0,
            },
            {
              id: 'op_main_door',
              type: 'entry_door',
              wall: 'north',
              offset: 6.5,
              width: 1.0,
              height: 2.15,
              sillHeight: 0.0,
            },
          ],
        },
      ],
    },
  },
];
